export const COLORS = {
  primary: "bg-[#1F2937] text-white",
  secondary: "bg-gray-100 text-gray-700",
  danger: "bg-red-600 text-white",
  success: "bg-green-600 ",
  border: "border-gray-300",
  heading: "text-gray-900",
  subtext: "text-gray-600",
  inputBorderError: "border-red-500",
  disabledButton: "opacity-50",
  white: "bg-white",
  errorText: "text-red-500",
  input: "w-full border rounded p-2",
  gradientBg: "bg-gradient-to-br from-gray-900 via-gray-800 to-gray-600",
  gradientText:
    "text-transparent bg-clip-text bg-gradient-to-r from-white to-gray-300",
  whiteText: "text-white",
  blackText: "text-black",
  grayText: "text-gray-500",
  grayBg: "bg-gray-100",
  lightGrayBg: "bg-gray-50",
  darkGrayBg: "bg-gray-800",
  lightGrayText: "text-gray-400",
  darkGrayText: "text-gray-800",
  lightBlueBg: "bg-blue-50",
  lightBlueText: "text-blue-500",
  lightGreenBg: "bg-green-50",
  lightGreenText: "text-green-500",
  lightRedBg: "bg-red-50",
  lightRedText: "text-red-500",
  lightYellowBg: "bg-yellow-50",
  lightYellowText: "text-yellow-500",
  lightPurpleBg: "bg-purple-50",
  lightPurpleText: "text-purple-500",
  gradientButton:
    "bg-[linear-gradient(92deg,_#FF855E_22.97%,_rgba(106,_42,_255,_0.95)_77.03%)] text-white",
};
